### ISSUE TITLE
[RESEARCH] Details

### ISSUE THREAD

**Issue by sergeevabc** [darcyclarke/octofiles#1]
Dear Darcy,
Could you be so kind to provide more details on how long files are kept
and whether it is possible to manage them in any way (list recent uploads, remove)?

**Comment by darcyclarke** [comment]
Hey @sergeevabc! Thanks for your question. The file uploads are here to stay as long as GitHub is (as far as I know, you can read more about them [here](https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests)).

In terms of file management, there isn't any native support for the features you list, beyond just uploading (I've dug through docs). I have reached out to some friends who work at GitHub though and might be able to get more insight (in case there is some kind of hidden API/functionality). 

The web extension itself might be able to track files you've uploaded utilizing localstorage/cookies... if that's something you'd be interested in, I may add that.

**Comment by darcyclarke** [comment]
@sergeevabc I've now added support for file management, to some extent. You can now see previously uploaded files and can *remove* them from the listing (note: this does not delete them from existence and they will still be publicly available to anyone you've shared the link with).

Check out the updated screen recording/gif in the [readme](https://github.com/darcyclarke/octofiles/#octofiles) to see it in action or just [install/update your extension](https://github.com/darcyclarke/octofiles/#install).

I've also added a [F.A.Q.](https://github.com/darcyclarke/octofiles/#faq) section to try and address an other questions someone may have about the implementation.

**Comment by sergeevabc** [comment]
@darcyclarke, a Github account is required for this extension to work, otherwise a user is redirected to Github sign-in page, consider adding a mention to FAQ. This begs the question, will the links be valid if the account has been suspended by admins? Also, a link to Firefox addon page should be fixed as follows:
```
https://addons.mozilla.org/en-US/developers/addon/octofiles/edit
↓
https://addons.mozilla.org/en-US/firefox/addon/octofiles/
```
And that page still lists version 0.2.0 whereas Chrome’s one lists 1.0.0.

**Comment by darcyclarke** [comment]
@sergeevabc  I'm not quite sure about whether or not the files are 100% attached to your GitHub account but I will make that more explicit in the FAQ section. I've also fixed the firefox add-on link (thanks for that).
